spring:
  profiles:
    active: hangzhou

server:
  port: 9119
  servlet:
    context-path: /zhx

# pagehelper properties
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  pageSizeZero: true
  reasonable: false
  params: pageNum=pageHelperStart;pageSize=pageHelperRows;
  supportMethodsArguments: false
