spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.75.47.142:3306/zhx?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      filters: stat,wall
  redis:
    host: 47.75.47.142
    port: 6379
    password: redis


mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    xyz.zaijushou.zhx : debug

xyz:
  zaijushou:
    zhx:
      token:
        sign-key: zaijushouzhx
      redis:
        login-token-expire-time: 30
      page:
        start-page: 1
        default-page-size: 10