spring:
  profiles:
    active: hangzhou
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 256MB

server:
  port: 9119
#  servlet:
#    context-path: /

# pagehelper properties
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  pageSizeZero: true
  reasonable: false
  params: pageNum=pageHelperStart;pageSize=pageHelperRows;
  supportMethodsArguments: false

logging:
  config: classpath:logging/logback-${spring.profiles.active}.xml