spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.25.205:1433;databasename=zhx
    # url: jdbc:sqlserver://172.16.0.25:1433;databasename=zhx
    username: sa
    password: frsoft@2019
    initialSize: 10
    minIdle: 5
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    druid:
      filters: stat,wall
  redis:
    host: 127.0.0.1
    port: 7777
    password: redis
    timeout: 50000
    jedis:
      pool:
        max-idle: 30
        min-idle: 10
        max-active: 500
        max-wait: 30000

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    xyz.zaijushou.zhx : debug

xyz:
  zaijushou:
    zhx:
      token:
        sign-key: zaijushouzhx
      redis:
        login-token-expire-time: 14400  #10天
      page:
        start-page: 1
        default-page-size: 10
      role:
        admin-judge: true #管理员权限开关，打开时，代码中需要判断是否有管理员权限

rar_path: d:/module/众汇信催收系统导入模板.rar
archive_path: d:/module/案人数据导入模板.xls
case_path: d:/module/案件导入模板.rar
detailFile_path: d:/detailFile/
userFile_path: d:/module/在职员工导入模板.rar