spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.75.47.142:3306/zhx?useSSL=false
    username: root
    password: root
    druid:
      filters: stat,wall
  redis:
    host: 47.75.47.142
    port: 6379
    password: redis


mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    xyz.zaijushou.zhx : debug