spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #url: jdbc:mysql://116.62.124.251:3306/zhx?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    url: jdbc:sqlserver://116.62.124.251:1433;databasename=zhx
    username: sa
    password: Qf@1985qweasdzxc
    initialSize: 10
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    druid:
      filters: stat,wall
  redis:
    host:  127.0.0.1
    port: 7777
    password: redis
    timeout: 50000
    maxTotal: 100
    maxIdle: 20
    maxWaitMillis: 10000
    testOnBorrow : true
    testOnReturn: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    xyz.zaijushou.zhx : debug

xyz:
  zaijushou:
    zhx:
      token:
        sign-key: zaijushouzhx
      redis:
        login-token-expire-time: 14400  #10天
      page:
        start-page: 1
        default-page-size: 10
      role:
        admin-judge: true #管理员权限开关，打开时，代码中需要判断是否有管理员权限


rar_path: c:/众汇信催收系统导入模板.rar
archive_path: c:/案人数据导入模板.xls
case_path: c:/案件导入模板.rar
detailFile_path: d:/detailFile/
userFile_path: c:/在职员工导入模板.rar