spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhx?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: qifei
    druid:
      filters: stat,wall
  redis:
    host: localhost
    port: 6379
    password: redis


mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    xyz.zaijushou.zhx : debug

xyz:
  zaijushou:
    zhx:
      token:
        sign-key: zaijushouzhx
      redis:
        login-token-expire-time: 14400  #10天
      page:
        start-page: 1
        default-page-size: 10